### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/idnits#25]
After installing locally to my home directory (since I can't install with `-g` on this box):
```shell
# ~/node_modules/@ietf-tools/idnits/cli.js draft-ietf-ace-cmpv2-coap-transport-09.txt 
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

[Error: ENOENT: no such file or directory, open './package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './package.json'
}

Node.js v18.13.0
```

**Comment by rjsparks** [comment]
Don't try to install @ietf-tools/idnits if you are developing. (You may need to restore package-lock.json and package.json).
Just use `npm install` as noted further down the readme.

I can get to the point where the tests pass, but I can't yet run the CLI (I have an older node and it insists on v18 or greater.

**Comment by rjsparks** [comment]
I got node 18 working, and the cli now behaves as expected (very limited so far).

**Comment by NGPixel** [comment]
In your case, you would need to cd into `~/node_modules/@ietf-tools/idnits/` first, then run `node cli.js` from there.

However, it might be a better idea to simply use `npx @ietf-tools/idnits <args>` which should download the package in a local cache, rather than installing globally.

~*Edit:* the path is still wrong using npx... Looking into it...~
*Edit:* using npx is now working as expected.
