### ISSUE TITLE
Idnits generates false positive for figures with Unicode characters

### ISSUE THREAD

**Issue by kszarkowicz** [ietf-tools/idnits#35]
I have draft that uses Unicode characters in drawing (https://www.ietf.org/archive/id/draft-smn-idr-inter-domain-ibgp-03.txt). Running this draft through https://author-tools.ietf.org/idnits results in 151 errors as follows:

"Line appears to be too long, but this could be caused by non-ascii characters in UTF-8 encoding"

Similar issue was opened in the past (https://github.com/ietf-tools/datatracker/issues/2574), which suppose to be fixed. However, false positive are still there.

**Comment by kesara** [comment]
@kszarkowicz, The new version of `idnits` is called [`idnits v3`](https://github.com/ietf-tools/idnits/tree/v3). It's still in alpha stage of the development.
It's available on author tools from https://author-tools.ietf.org/idnits3

Seems like this issue is not occurring in v3: https://author-tools.ietf.org/api/idnits3?url=https://www.ietf.org/archive/id/draft-smn-idr-inter-domain-ibgp-03.txt

BTW idnits v3 works better with xml files.
There are few unrelated errors when you submit an XML file: https://author-tools.ietf.org/api/idnits3?url=https://www.ietf.org/archive/id/draft-smn-idr-inter-domain-ibgp-03.xml

**Comment by kszarkowicz** [comment]
OK. That is good. When idnits3 is expected to be officially released and used during shepherd's reviews?

**Comment by rjsparks** [comment]
It will still be some months before that is generally available. In the meantime, you the warning is not a blocking warning.
(Modifying the older idnits is quite difficult - it's a collection of sed-like things in a bash script, and character encoding nuance may be beyond it).

**Comment by kszarkowicz** [comment]
OK. Let's close this issue.
